### PR TITLE
keep looper running on adversities

### PR DESCRIPTION
**Pull request by kdiogenes**
Avoids that an exception terminates the looper thread.

### CODE REVIEW

**Comment by kdiogenes** [comment]
With the patch, I'm running puma-cloudwatch in the last 3 days without any interruption.

**Comment by kdiogenes** [comment]
In these last 3 days I get the following errors:
Exception | Count
--------------|---------
The parameter MetricData is required. (Aws::CloudWatch::Errors::MissingParameter) | 23570
cannot load such file -- puma_cloudwatch/metrics/fetcher (LoadError) | 90
uninitialized constant PumaCloudwatch::Metrics::Fetcher (NameError) | 3

I'm also not in favor of rescuing the general Exception. Before proposing this I decided to look at how puma handle this kind of situation, and they do exactly this: https://github.com/puma/puma/commit/0d8f026172bf051fcd60f698b9ff4a9f893c9ef4

A more recent commit added the log message: https://github.com/puma/puma/commit/181c47278114b5397183c2a79be8c14a95d96238

I'm running puma 4.3.3 and ruby 2.5.5.

**Comment by tongueroo** [comment]
Cool. Thanks. Maybe `Aws::CloudWatch::Errors::MissingParameter` is something that maybe puma-cloudwatch should handle. 

Going with this fix right now. Unsure if it's worth time time to track down `Aws::CloudWatch::Errors::MissingParameter`. Thanks for the fix.

**Comment by kdiogenes** [comment]
@tongueroo, did you forget to send this version to rubygems.org? :yum:

**Comment by tongueroo** [comment]
Opps. Actually released it this time. Thanks!

**Pull request merged**
